export default {
  'events': {
    'events': [
      {
        'category': 'MAIN',
        'subcategory': 'send',
        'channel': '11',
        'timestamp': 1047.8965459996834,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'on',
        'channel': '11',
        'timestamp': 1552.3589620003477,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'on',
        'channel': '11',
        'timestamp': 2053.0809789998457,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'send',
        'channel': '11',
        'timestamp': 2554.774876999669,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'send',
        'channel': '11',
        'timestamp': 3054.8572019999847,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'on',
        'channel': '11',
        'timestamp': 3556.2376159997657,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'on',
        'channel': '11',
        'timestamp': 4057.623602000065,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'send',
        'channel': '11',
        'timestamp': 4558.2038509994745,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'send',
        'channel': '12',
        'timestamp': 5058.711655999534,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'on',
        'channel': '12',
        'timestamp': 5560.008134000003,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'on',
        'channel': '12',
        'timestamp': 6060.414134999737,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'send',
        'channel': '12',
        'timestamp': 6560.833514000289,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'send',
        'channel': '12',
        'timestamp': 7061.7711039995775,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'on',
        'channel': '12',
        'timestamp': 7562.246077999473,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'on',
        'channel': '12',
        'timestamp': 8063.6153400000185,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'send',
        'channel': '12',
        'timestamp': 8564.870804999955,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'send',
        'channel': '11',
        'timestamp': 9064.859900999814,
        'interceptionStrategy': 'send',
      },
      {
        'category': 'MAIN',
        'subcategory': 'on',
        'channel': '11',
        'timestamp': 9565.589948999695,
        'interceptionStrategy': 'on',
      },
      {
        'category': 'RENDERER',
        'subcategory': 'on',
        'channel': '11',
        'timestamp': 10068.031475000083,
        'interceptionStrategy': 'on',
      },
    ],
    'selectedEvents': [],
    'filterToggle': false,
    'selectedChannel': [],
    'selectedMin': 0,
    'selectedMax': 100,
    'options': {
      'channel': [
        '11',
        '12',
      ],
      'timestamp': {
        'min': 1047.8965459996834,
        'max': 10068.031475000083,
      },
      'category': [
        'MAIN',
        'RENDERER',
      ],
      'subcategory': [
        'send',
        'on',
      ],
    },
  },
  'graph': {
    'graphRenderCount': 0,
  },
};
